[project]
name = "beancount-danish"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beancount>=3.2.0",
    "beangulp>=0.2.0",
    "fava>=1.30.9",
    "jinja2>=3.1.6",
    "weasyprint>=67.0",
]
